<field:daoyan itemname="导演" autofield="1" notsend="0" type="text" isnull="true" islist="0" default=""  maxlength="250" page="">
</field:daoyan>
<field:shangying itemname="上映日期" autofield="1" notsend="0" type="text" isnull="true" islist="0" default=""  maxlength="250" page="">
</field:shangying>
<field:videourl itemname="播放地址" autofield="1" notsend="0" type="textdata" isnull="true" islist="0" default=""  maxlength="250" page="">
</field:videourl>
<field:bofangcishu itemname="播放次数" autofield="1" notsend="0" type="text" isnull="true" islist="0" default=""  maxlength="250" page="">
</field:bofangcishu>
<field:pingfen itemname="评分" autofield="1" notsend="0" type="text" isnull="true" islist="0" default=""  maxlength="250" page="">
</field:pingfen>
<field:bofangyuan itemname="播放源" autofield="1" notsend="0" type="text" isnull="true" islist="0" default=""  maxlength="250" page="">
</field:bofangyuan>
<field:biaoqian itemname="标签" autofield="1" notsend="0" type="text" isnull="true" islist="0" default=""  maxlength="250" page="">
</field:biaoqian>
<field:jianjie itemname="简介" autofield="1" notsend="0" type="text" isnull="true" islist="0" default=""  maxlength="250" page="">
</field:jianjie>
<field:reping itemname="热评" autofield="1" notsend="0" type="int" isnull="true" islist="0" default=""  maxlength="250" page="">
</field:reping>
<field:zhuyan itemname="主演" autofield="1" notsend="0" type="text" isnull="true" islist="0" default=""  maxlength="250" page="">
</field:zhuyan>
<field:gaishu itemname="概述" autofield="1" notsend="0" type="text" isnull="true" islist="0" default=""  maxlength="250" page="">
</field:gaishu>
