
<m:item name='评论管理' link='duoshuo.php?action=manageComments' rank='' target='main' />
<m:item name='本地设置' link='duoshuo.php?action=localConfig' rank='' target='main' />
<m:item name='用户管理' link='duoshuo.php?action=adminUsers' rank='' target='main' />
<m:item name='评论框设置' link='duoshuo.php?action=adminSettings' rank='' target='main' />
<m:item name='帮助文档' link='duoshuo.php?action=helpDocument' rank='' target='main' />
