<a href="[field:arcurl/]" class="external color-default">
            	<li>
                	<div class="vpl_remonForyou_list_left">
                    	<img src="[field:litpic/]" class="tuijian-pic" style="width: 100%;height: 100%;"/>
                    </div>
                    <div class="vpl_remonForyou_list_right">
                    	<div class="vpl_remonForyou_list_right_des">
                        	<p style="font-size:0.8rem;margin:0;padding:0;">[field:title/]</p>
                            <p style="font-size:0.7rem;color:#909090;margin-top:0.17rem;">[field:gaishu/]</p>
                        </div>
                        <div class="vpl_remonForyou_list_right_go iconfont icon-yingdaicon10"></div>
                    </div>
                </li>
                </a>