<?php
$z[0]=Array("arclist","\r\n	         <div class=\"swiper-slide\"><a href=\"[field:arcurl/]\" class=\"external\"><img src=\"[field:litpic/]\" alt=\"\"></a></div>\r\n	       	",2347,2551);
$z[0][4]['typeid']="1";
$z[0][4]['row']="6";
$z[0][4]['orderby']="sortrank";
$z[1]=Array("arclist","\r\n	  	<a href=\"[field:arcurl/]\" class=\"external\"><img src=\"[field:litpic/]\" alt=\"\"></a>\r\n	  	<div class=\"content-bottom\" style=\"padding-bottom: .2rem;\">\r\n	  		<h4>[field:title/]</h4>\r\n	  		<p>[field:shorttitle/]</p>\r\n	  	</div>\r\n	  	",2923,3232);
$z[1][4]['flag']="a";
$z[1][4]['typeid']="8";
$z[1][4]['row']="1";
$z[1][4]['orderby']="sortrank";
$z[2]=Array("arclist","\r\n	  		<div class=\"item\">\r\n	  			<a href=\"[field:arcurl/]\" class=\"external\"><img src=\"[field:litpic/]\" alt=\"\"></a>\r\n	  			<div class=\"content-bottom\">\r\n	  		      <h4>[field:title/]</h4>\r\n	  		      <p>[field:shorttitle/]</p>\r\n	  	        </div>\r\n	  		</div>\r\n	  		",3461,3802);
$z[2][4]['flag']="h";
$z[2][4]['typeid']="8";
$z[2][4]['row']="4";
$z[2][4]['orderby']="sortrank";
$z[3]=Array("arclist","\r\n	  		<div class=\"item\">\r\n	  			<a href=\"[field:arcurl/]\" class=\"external\"><img src=\"[field:litpic/]\" alt=\"\"></a>\r\n	  			<div class=\"content-bottom\">\r\n	  		      <h4>[field:title/]</h4>\r\n	  		      <p>[field:shorttitle/]</p>\r\n	  	        </div>\r\n	  		</div>\r\n	  		",4219,4560);
$z[3][4]['flag']="f";
$z[3][4]['typeid']="8";
$z[3][4]['row']="4";
$z[3][4]['orderby']="sortrank";
$z[4]=Array("arclist","\r\n	  		<div class=\"item\">\r\n	  			<a href=\"[field:arcurl/]\" class=\"external\"><img src=\"[field:litpic/]\" alt=\"\"></a>\r\n	  			<div class=\"content-bottom\">\r\n	  		      <h4>[field:title/]</h4>\r\n	  		      <p>[field:shorttitle/]</p>\r\n	  	        </div>\r\n	  		</div>\r\n	  		",4983,5324);
$z[4][4]['flag']="s";
$z[4][4]['typeid']="8";
$z[4][4]['row']="4";
$z[4][4]['orderby']="sortrank";
$z[5]=Array("arclist","\r\n	  		<div class=\"item\">\r\n	  			<a href=\"[field:arcurl/]\" class=\"external\"><img src=\"[field:litpic/]\" alt=\"\"></a>\r\n					<!--<div class=\"howlongtime\">\r\n						03:30  \r\n					</div>-->\r\n	  			<div class=\"content-bottom\">\r\n	  		      <h4>[field:title/]</h4>\r\n	  		      <p>[field:shorttitle/]</p>\r\n	  	        </div>\r\n	  		</div>\r\n	  		",5748,6150);
$z[5][4]['typeid']="10";
$z[5][4]['row']="4";
$z[5][4]['orderby']="sortrank";

?>