<?php
$z[0]=Array("arclist","  		\r\n			  		<div class=\"item\">\r\n			  			<a href=\"[field:arcurl/]\" class=\"external\"><img class=\"lazy\" data-src=\"[field:litpic/]\" src=\"/images/shipin-jiazai.jpg\" alt=\"\"></a>\r\n			  			<div class=\"content-bottom\">\r\n			  		      <h4>[field:title/]</h4>\r\n			  		      <p>[field:shorttitle/]</p>\r\n			  	        </div>\r\n			  		</div>\r\n			  		",979,1384);
$z[0][4]['typeid']="8";
$z[0][4]['row']="200";
$z[0][4]['orderby']="sortrank";

?>